// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

import (
	"context"
	"time"
)

type User struct {
	ID        string
	Name      string
	Username  string
	Email     string
	Role      string
	CreatedAt time.Time
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, role, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, username, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, username, email, role, created_at
`

type CreateUserParams struct {
	ID           string
	Name         string
	Username     string
	Email        string
	PasswordHash *string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
